### ISSUE TITLE
OpenCV ROI out-of-bounds

### ISSUE THREAD

**Issue by Willy-NotSpe** [fraser-in-school/video_synopsis-#3]
File "get_video.py", line 39, in poisson_integration
    poisson_image = cv2.seamlessClone(object_image, background_img, mask, center, style)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-6amqbhlx/opencv/modules/core/src/matrix.cpp:465: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

請問作者這問題該如何處理?

**Comment by zhanghao1903** [comment]
看描述，是不是宽度或者高度的参数小于0了。这种事情百度就可以了



---Original---

**Comment by Willy-NotSpe** [comment]
好的，我再試試，謝謝！

**Comment by xiuzhizheng** [comment]
在get_video.py中
background_img = cv2.imread('./background.jpg')
这一句路径错啦，读出来的图片是空的，就报错啦

**Comment by Willy-NotSpe** [comment]
Because the video_width & video_height is hard code in location.py
So even modify the constant.py, the error may be occur in produce video step when the video_height & video_width doesn't match in the above file.
